### ISSUE TITLE
Improve game

### ISSUE THREAD

**Issue by ColdIV** [ColdIV/Favipong#1]
This game was made in haste and it could use some love.
It is not really playable right now.

I only create this one issue because I don't know what other changes could be made, anything that improves the game is welcome I guess.

Possible Changes
- Make it more "smooth"
- ~~After someone scored a point the ball should start at the paddle, not the middle~~
- ~~Add "restart game" function~~
- ~~Add Multiplayer (Switch between Player vs Player and Player vs AI)~~
- ...

**Comment by robertbegna** [comment]
hey sounds interesting, i'd like to work on this

**Comment by ColdIV** [comment]
Restart button has been added #3

**Comment by ColdIV** [comment]
Multiplayer mode has been added #2

**Comment by ColdIV** [comment]
Ball now starts at paddle after scoring a point #4
